version: '3.8'
services:

    # Application
    app:
        build:
            context: .
            dockerfile: ./docker/app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "database"

    # Web Server
    web:
        image: nginx:1.21
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs/:/var/log/nginx/
        depends_on:
            - "app"
        ports:
            - 8081:80

    # Database
    database:
        image: mysql:8.0
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - 33061:3306

 # Database management
    pma:
        image: phpmyadmin:5.1
        environment:
             PMA_HOST: database
             PMA_PORT: ${DB_PORT}
        depends_on:
            - database
        ports:
            - 8888:80

volumes:
    dbdata:
